---
- import_playbook: pingpong.yaml

- hosts: "{{ server }}"
  gather_facts: no
  become: yes
  roles:
    - server-setup
    - cri-installation
    - cluster-common-installation

- hosts: masters[0]
  gather_facts: no
  become: yes
  roles:
    - create-cluster-token

- hosts: "{{ server }}"
  gather_facts: no
  become: yes
  roles:
    - name: join-k8s-cluster
      vars:
        server_type: worker