---
- name: Check the connectivity of Servers
  hosts: all
  gather_facts: no
  tasks:
    - name: wait for instances to become available
      wait_for_connection:

    - name: Gather facts for first time
      setup: