- hosts: "{{ hosts | default('all') }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Reset kubeadm
      command: kubeadm reset -f

    # Should be extract to a cleanup-cni role
    - name: Cleanup "{{ cni | default('flannel') }} CNI network bridge"
      shell: ip link delete cni0
      ignore_errors: yes

    - name: Cleanup "{{ cni | default('flannel') }} CNI"
      shell: ip link delete flannel.1
      ignore_errors: yes

    - name: Cleanup "{{ cni | default('flannel') }} CNI info"
      file: 
        path: /run/flannel
        state: absent
    #

- hosts: masters
  gather_facts: no
  become: yes
  tasks:
    - name: remove /etc/kubernetes/manifests/, /etc/haproxy/ and .kube
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes/manifests
        - /etc/haproxy
        - /etc/kubernetes/pki
        - ./kubeadm-config.yaml