- hosts: "{{ hosts | default('all') }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Reset kubeadm
      command: kubeadm reset -f

    # Should be extract to a cleanup-cni role
    - name: Cleanup "{{ cni | default('flannel') }} CNI info"
      file: 
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/cni
        - /run/flannel
        - /var/lib/cni
    
    - name: Remove /etc/kubernetes
      file: 
        path: /etc/kubernetes
        state: absent

    # kubelet will look for this file to determine which container runtime should be used
    - name: Remove /etc/default/kubelet
      file: 
        path: /etc/default/kubelet
        state: absent

    - name: Cleanup "{{ cni | default('flannel') }} CNI network bridge"
      shell: "ip link set {{ item }} down"
      ignore_errors: yes
      loop: 
        - cni0
        - flannel.1

    - name: Cleanup "{{ cni | default('flannel') }} CNI"
      shell: "ip link delete {{ item }}"
      ignore_errors: yes
      loop: 
        - cni0
        - flannel.1

- hosts: localhost
  gather_facts: no
  tasks:
    - name: remove master and worker join command
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - master-join-command
        - worker-join-command

- hosts: masters
  gather_facts: no
  become: yes
  tasks:
    - name: remove /etc/haproxy/ and .kube
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/haproxy
        - ./kubeadm-config.yaml
        - ./.kube