- name: install Docker
  apt:
    name: docker.io
    state: present

- name: Set up the Docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: start Docker service
  service:
    name: docker
    state: restarted
    enabled: yes
