- name: install Docker
  apt:
    name: docker.io
    state: present

- name: Set up the Docker daemon
  shell:
    cmd: |
      cat <<EOF | sudo tee /etc/docker/daemon.json
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
      EOF

- name: start Docker service
  service:
    name: docker
    state: restarted
    enabled: yes
