- name: Copy the join command to server location
  copy: 
    src: join-command 
    dest: /tmp/join-command.sh 
    mode: 0777
      
- name: Join the node to cluster
  become: yes
  command: sh /tmp/join-command.sh