- name: Disabling Swap on all nodes
  shell: swapoff -a

- name: Commenting Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: "(^/.*swap*)"
    replace: '# \1'

- name: install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Set up the Docker daemon
  shell:
    cmd: |
      cat <<EOF | sudo tee /etc/docker/daemon.json
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
      EOF

- name: start Docker service
  service:
    name: docker
    state: restarted
    enabled: yes

- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present

- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: "kubernetes"

- name: install kubelet & kubeadm
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  loop:
    - kubelet=1.20.0-00
    - kubeadm=1.20.0-00

- name: Enabling Bridge Firewall Rule
  shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"