- name: Copy the {{server_type | default('worker') }} join command to server location
  copy: 
    src: "{{server_type | default('worker') }}-join-command"
    dest: /tmp/join-command.sh 
    mode: 0777

- name: "{{server_type | default('worker') }} : run the join command"
  command: sh /tmp/join-command.sh